In [1]:
############################################################################################ 
# Data Munging for Tableau
# Gary Schulke
# February 02, 2020
############################################################################################
############################################################################################
############################################################################################

In [2]:
############################################################################################ 
# Section 1
# 
############################################################################################

In [3]:
import pandas as pd

In [4]:
# Finish cleaning with Pandas
# Comment / uncomment out file and periodTags as need.
# The path to our CSV file

source_folder = './'

file = "201901-citibike-tripdata.csv"

In [31]:
import glob

files = [f for f in glob.glob(source_folder + "**/*-citibike-tripdata.csv", recursive=True)]

for each in files:
    print(each)

.\201901-citibike-tripdata.csv
.\201902-citibike-tripdata.csv
.\201903-citibike-tripdata.csv
.\201904-citibike-tripdata.csv
.\201905-citibike-tripdata.csv
.\201906-citibike-tripdata.csv
.\201907-citibike-tripdata.csv
.\201908-citibike-tripdata.csv
.\201909-citibike-tripdata.csv
.\201910-citibike-tripdata.csv
.\201911-citibike-tripdata.csv
.\201912-citibike-tripdata.csv

In [32]:
# Read data into pandas
df = pd.read_csv(source_folder + files[1])
# Take a look at it.
df.iloc[0:10]

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,219,2019-02-01 00:00:06.2570,2019-02-01 00:03:46.1090,3494.0,E 115 St & Lexington Ave,40.797911,-73.942300,3501.0,E 118 St & Madison Ave,40.801487,-73.944251,33450,Subscriber,1989,1
1,143,2019-02-01 00:00:28.0320,2019-02-01 00:02:51.7460,438.0,St Marks Pl & 1 Ave,40.727791,-73.985649,236.0,St Marks Pl & 2 Ave,40.728419,-73.987140,25626,Subscriber,1990,1
2,296,2019-02-01 00:01:13.9870,2019-02-01 00:06:10.7340,3571.0,Bedford Ave & Bergen St,40.676368,-73.952918,3549.0,Grand Ave & Bergen St,40.678045,-73.962408,35568,Subscriber,1987,1
3,478,2019-02-01 00:01:14.1520,2019-02-01 00:09:12.7870,167.0,E 39 St & 3 Ave,40.748901,-73.976049,477.0,W 41 St & 8 Ave,40.756405,-73.990026,25045,Subscriber,1964,2
4,225,2019-02-01 00:01:49.3410,2019-02-01 00:05:34.4980,3458.0,W 55 St & 6 Ave,40.763094,-73.978350,3443.0,W 52 St & 6 Ave,40.761330,-73.979820,34006,Subscriber,1979,1
5,457,2019-02-01 00:02:04.0010,2019-02-01 00:09:41.5640,3078.0,Broadway & Roebling St,40.709248,-73.960631,3016.0,Kent Ave & N 7 St,40.720368,-73.961651,33858,Subscriber,1981,2
6,175,2019-02-01 00:02:12.2960,2019-02-01 00:05:08.0930,411.0,E 6 St & Avenue D,40.722281,-73.976687,317.0,E 6 St & Avenue B,40.724537,-73.981854,24839,Subscriber,1995,1
7,248,2019-02-01 00:02:13.0450,2019-02-01 00:06:21.3960,3628.0,Lenox Ave & W 117 St,40.802557,-73.949078,3506.0,Lexington Ave & E 120 St,40.801307,-73.939817,31798,Subscriber,1991,1
8,541,2019-02-01 00:02:28.0750,2019-02-01 00:11:29.5490,293.0,Lafayette St & E 8 St,40.730207,-73.991026,383.0,Greenwich Ave & Charles St,40.735238,-74.000271,32175,Subscriber,1981,0
9,406,2019-02-01 00:03:06.5420,2019-02-01 00:09:53.4310,380.0,W 4 St & 7 Ave S,40.734011,-74.002939,3263.0,Cooper Square & Astor Pl,40.729515,-73.990753,27688,Subscriber,1973,2

In [6]:
# Get a list of all of our columns, columns named deleteX will be deleted for easy reference.
df.columns

Index(['tripduration', 'starttime', 'stoptime', 'start station id',
       'start station name', 'start station latitude',
       'start station longitude', 'end station id', 'end station name',
       'end station latitude', 'end station longitude', 'bikeid', 'usertype',
       'birth year', 'gender'],
      dtype='object')

In [10]:
# Rename the columns
headings = {'tripduration':'tripduration', 'starttime':'starttime', 'stoptime':'stoptime',
         'start station id':'start_station_id', 'start station name':'start_station_name',
         'start station latitude':'start_station_latitude', 
         'start station longitude':'start_station_longitude', 
         'end station id':'end_station_id','end station name':'end_station_name',
         'end station latitude':'end_station_latitude', 
         'end station longitude':'end_station_longitude', 
         'bikeid':'bikeid', 'usertype':'usertype', 'birth year':'birth_year', 
         'gender':'gender'}
df = df.rename(columns=headings)
df.head()

,tripduration,starttime,stoptime,start_station_id,start_station_name,start_station_latitude,start_station_longitude,end_station_id,end_station_name,end_station_latitude,end_station_longitude,bikeid,usertype,birth_year,gender
0,320,2019-01-01 00:01:47.4010,2019-01-01 00:07:07.5810,3160.0,Central Park West & W 76 St,40.778968,-73.973747,3283.0,W 89 St & Columbus Ave,40.788221,-73.970416,15839,Subscriber,1971,1
1,316,2019-01-01 00:04:43.7360,2019-01-01 00:10:00.6080,519.0,Pershing Square North,40.751873,-73.977706,518.0,E 39 St & 2 Ave,40.747804,-73.973442,32723,Subscriber,1964,1
2,591,2019-01-01 00:06:03.9970,2019-01-01 00:15:55.4380,3171.0,Amsterdam Ave & W 82 St,40.785247,-73.976673,3154.0,E 77 St & 3 Ave,40.773142,-73.958562,27451,Subscriber,1987,1
3,2719,2019-01-01 00:07:03.5450,2019-01-01 00:52:22.6500,504.0,1 Ave & E 16 St,40.732219,-73.981656,3709.0,W 15 St & 6 Ave,40.738046,-73.996430,21579,Subscriber,1990,1
4,303,2019-01-01 00:07:35.9450,2019-01-01 00:12:39.5020,229.0,Great Jones St,40.727434,-73.993790,503.0,E 20 St & Park Ave,40.738274,-73.987520,35379,Subscriber,1979,1

In [ ]:
#df.drop(['Unnamed: 8'], axis = 1, inplace = True) 
#df = df.dropna()

In [11]:
df.dtypes

tripduration                 int64
starttime                   object
stoptime                    object
start_station_id           float64
start_station_name          object
start_station_latitude     float64
start_station_longitude    float64
end_station_id             float64
end_station_name            object
end_station_latitude       float64
end_station_longitude      float64
bikeid                       int64
usertype                    object
birth_year                   int64
gender                       int64
dtype: object

In [18]:
df4060 = df[df['birth_year'].isin([1950, 1960, 1970, 1980])]

In [19]:
df4060.head()

,tripduration,starttime,stoptime,start_station_id,start_station_name,start_station_latitude,start_station_longitude,end_station_id,end_station_name,end_station_latitude,end_station_longitude,bikeid,usertype,birth_year,gender
36,813,2019-01-01 00:27:12.5070,2019-01-01 00:40:45.5940,3165.0,Central Park West & W 72 St,40.775794,-73.976206,450.0,W 49 St & 8 Ave,40.762272,-73.987882,32899,Subscriber,1970,1
49,711,2019-01-01 00:31:36.9290,2019-01-01 00:43:28.0580,346.0,Bank St & Hudson St,40.736529,-74.006180,529.0,W 42 St & 8 Ave,40.757570,-73.990985,29078,Subscriber,1980,1
53,220,2019-01-01 00:34:01.4710,2019-01-01 00:37:42.2550,316.0,Fulton St & William St,40.709560,-74.006536,195.0,Liberty St & Broadway,40.709056,-74.010434,20120,Subscriber,1980,1
57,837,2019-01-01 00:35:04.5250,2019-01-01 00:49:01.6370,458.0,11 Ave & W 27 St,40.751396,-74.005226,334.0,W 20 St & 7 Ave,40.742388,-73.997262,29066,Subscriber,1960,1
61,268,2019-01-01 00:37:57.8670,2019-01-01 00:42:26.2600,439.0,E 4 St & 2 Ave,40.726281,-73.989780,150.0,E 2 St & Avenue C,40.720874,-73.980858,20727,Subscriber,1980,1

In [24]:
len(df)

967287

In [25]:
len(df4060)

59212

In [ ]:

df4060.to_csv(source_folder + file_name + '4070.csv'